name: MovieFlix CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/movieflix:latest .

      - name: Run container (teste)
        run: docker run -d -p 8000:8000 ${{ secrets.DOCKER_USER }}/movieflix

      - name: Login Docker Hub
        run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/movieflix:latest
